### ISSUE TITLE
Mod not loading

### ISSUE THREAD

**Issue by jthotshot** [Loyalists/gflh1#1]
I was really looking forward to this so I bought MWR as soon as it was released.  I think I got the H1-mod develop build figured out, but every time it's still only loading the checker background.

I tried the alternative listed but that just immediately crash the game whenever I try to run it after replacing the eng_h1_mod_common.ff file.  I've been at it all day and downloaded the game twice to try to fix this but still can't get it to work.  Am I missing a step somewhere?

Thanks so much!

**Comment by Loyalists** [comment]
https://github.com/h1-mod/h1-mod/actions/runs/4478388098
Ensure you are using this build and when the game asks for an update, don’t

**Comment by jthotshot** [comment]
> https://github.com/h1-mod/h1-mod/actions/runs/4478388098 Ensure you are using this build and when the game asks for an update, don’t

Thanks for getting back so quickly!!

I tried this version and skipped all update.  The Mod option is not there if I don't update.  I am able to get into the game directly using h1-mod-gfl.bat, but it's still only the checker background (still no Mod option either).  I tried wiping everything and did a fresh download of MW:R but it still ended up looking the same.

**Comment by Loyalists** [comment]
I think I found the culprit - You have to disable Shader Preload in settings. 
First try to do something like moving or renaming the modded eng_h1_mod_common.ff or something else as long as the game can be launched without crashing. After tweaks are done move the file back to its original location.

**Comment by JJisAwwsome** [comment]
> I think I found the culprit - You have to disable Shader Preload in settings. First try to do something like moving or renaming the modded eng_h1_mod_common.ff or something else as long as the game can be launched without crashing. After tweaks are done move the file back to its original location.

I was having the same issue, but this got it working for me, thanks!

Just simply to reiterate for anyone else, the game will crash on launch if you have the copied and renamed  eng_h1_mod_common.ff file in C:/Users/[YOUR USERNAME]/AppData/Local/h1-mod/cdata/zone/english and have NOT YET diasbled Shader Preload. Like what Loyalists said, you can just simply remove the file, launch the game, disable Shader Preload, exit the game, move the the copied and renamed  eng_h1_mod_common.ff file back to C:/Users/[YOUR USERNAME]/AppData/Local/h1-mod/cdata/zone/english and then enjoy the game

One other thing, if you don't have the ability to select mods from the campaign menu, you may not have all the required files in C:/Users/[YOUR USERNAME]/AppData/Local/h1-mod, specifically if you're missing the cdata folder. Launching h1 and hitting update should get you the required files. 

If you hit update again after getting the mod to work, your copied and renamed eng_h1_mod_common.ff file will be replaced and the mod will go back to being all checker boardy and you'll need to go through the whole process again.

**Comment by jthotshot** [comment]
Thanks so much, I finally got it working.

The game seems to crash in the newly added obstacle crash, but luckily this is added content and doesn't affect the game progression.

Thanks so much for the speedy reply!

**Comment by mjkzy** [comment]
we're looking into a official fix for this on h1-mod

**Comment by Bluekiller201** [comment]
> 

Need a tutorial with a video tho, can't really understand how to do it.

**Comment by unknownx6** [comment]
i tried all the options and the mod is still not loading
